### PR TITLE
Added support for per-channel timezone offsets.

### PR DESCRIPTION
**Pull request by FiXato**
You can now create a file at CHANNEL_LOCATIONS_FILE that contains a
list of channels and (pytz) timezone location names.
All log files for specified channels from that point on will have their
timestamps adjusted to the given timezone.
If a channel is not specified in the config file, it will default to
the timezone specified by DEFAULT_TIMEZONE (which defaults to UTC).

I've started storing this info in a separate config file as I plan to
move all the other settings into a config file as well so people don't
need to edit the script (allowing the script to be re-used more easily).

### CODE REVIEW

**Comment by excid3** [comment]
Looks good. Is there any way of removing the pytz dependency? I was trying to keep this as simple as possible for installation.

**Comment by FiXato** [comment]
I couldn't really find a good way to have it take daylight savings time into account. I could make it just use a simple 1 hour offset, but then it would only be valid for half a year or till you manually update the config. PyTZ was the easiest solution I could find.
However, if someone doesn't have pytz, it should already just default to the old solution of using the computer's local time.

**Comment by excid3** [comment]
Fair enough. Would you mind updating the readme to include an example of how to setup this feature? After that I think it's good to go for merging.

**Comment by FiXato** [comment]
Sure, no problem. 
I still wish the world would get rid of DST though; it's a pain in the arse for developers :/

**Comment by excid3** [comment]
Totally agreed. Timezones are such a pain.

**Comment by FiXato** [comment]
Does this suffice? :)

**Comment by excid3** [comment]
Perfect!

**Pull request merged**
